import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import "./prosemirror.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "500",
  subsets: ["latin"],
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={roboto.className}>
      <body className=" p-6">
        <NextThemesProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          {children}
        </NextThemesProvider>

        <Toaster position="top-right" />
      </body>
    </html>
  );
}

import { headers } from "next/headers";
import { Toaster } from "@/components/ui/sonner";
export async function generateViewport(): Promise<any> {
  const userAgent = headers().get("user-agent");
  const isiPhone = /iphone/i.test(userAgent ?? "");
  return isiPhone
    ? {
        width: "device-width",
        initialScale: 1,
        maximumScale: 1, // disables auto-zoom on ios safari
      }
    : {};
}
